cluster: 
  sbatch
      --partition={resources.partition}
      --qos={resources.qos}
      --cpus-per-task={threads}
      --gpus={resources.gpus}
      --job-name=smk_{rule}
      --output=logs/{rule}_output_%j.txt
      --error=logs/{rule}_output_%j.txt
      --mem={resources.mem_mb}
      --nice=10000
      --time={resources.time}
default-resources:
      - partition=cpu_p
      - qos=cpu_normal
      - mem_mb=160000
      - gpus=0
      - time=48:00:00
max-threads: 12
use-conda: True
use-singularity: True
singularity-args:
      --bind /home/:/home/,/lustre/:/lustre/,/localscratch/:/localscratch/
jobs: 80
keep-going: True
restart-times: 0
