cluster: 
  sbatch
      --partition={resources.partition}
      --qos={resources.qos}
      --cpus-per-task={threads}
      --gpus={resources.gpus}
      --job-name=smk_{rule}
      --output=logs/{rule}_output_%j.txt
      --error=logs/{rule}_output_%j.txt
      --mem={resources.mem_mb}
      --nice=10000
      --time=24:00:00
default-resources:
      - partition=cpu_p
      - qos=cpu_normal
      - mem_mb=15000
      - gpus=0
set_resources:
  eval0_shared_gpu:
    - partition=gpu
    - qos=gpu_normal
    - gpus=1
  eval1_pre_gpu:
    - partition=gpu
    - qos=gpu_normal
    - gpus=1
max-threads: 12
use-conda: True
use-singularity: True
singularity-args:
      --bind /home/:/home/,/lustre/:/lustre/,/localscratch/:/localscratch/
jobs: 80
keep-going: True
restart-times: 0
