# when using relative paths: note that the working directory is the pwd of the terminal from where snakemake is run,
# this should be .../spapros-smk  (also possible: .../spapros-smk/workflow, might mess things up though)
DATA_DIR: /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data
DATA_DIR_TMP: /lustre/groups/ml01/workspace/lena.strasser/spapros-smk/data/tmp_data
RESULTS_DIR: results
SAVE_METHOD_SPECIFIC_OUTPUT: True # Whether to save method specific output of the selection methods (will be in RESULTS_DIR+"method_specific/{run}/")
PRELIMINARY_EVAL_SUMMARY: False # Whether to just summarise the currently available evaluation results and not run anything else.
# NOTE: PRELIMINARY_EVAL_SUMMARY can lead to wrong values for set ids that partially miss evaluation files!!!

selections:
  batch_permutations_bone_marrow:
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut.csv ]
      ct_key: [ cell_type ]
    selection_param:
      n: [ 50 ]
      method_specific_processing: [ False ]
      ct_key: [ cell_type ]
      batch_key: [ id ] # the default behaviour is batch_key=None
    methods:
      spapros

evaluations:
  eval_on_full_bone_marrow:
    batches: [ batch_permutations_bone_marrow ]
    selection_dataset: False
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      ct_key: [ cell_type ]
    metrics: [ forest_clfs, cluster_similarity ]  # forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
  eval_on_one_bone_marrow:
    batches: [ batch_permutations_bone_marrow ]
    selection_dataset: False
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut_one.csv ]
      ct_key: [ cell_type ]
    metrics: [ forest_clfs, cluster_similarity ]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]