# when using relative paths: note that the working directory is the pwd of the terminal from where snakemake is run,
# this should be .../spapros-smk  (also possible: .../spapros-smk/workflow, might mess things up though)
DATA_DIR: /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/raw_data
DATA_DIR_TMP: /lustre/groups/ml01/workspace/lena.strasser/spapros-smk/data/tmp_data
RESULTS_DIR: results
SAVE_METHOD_SPECIFIC_OUTPUT: True # Whether to save method specific output of the selection methods (will be in RESULTS_DIR+"method_specific/{run}/")
PRELIMINARY_EVAL_SUMMARY: False # Whether to just summarise the currently available evaluation results and not run anything else.
# NOTE: PRELIMINARY_EVAL_SUMMARY can lead to wrong values for set ids that partially miss evaluation files!!!

selections:
  batch_aware:
    datasets: [pbmc1k]
    #dataset_param:
    #  cells_per_ct_n_seeds : [4]
    selection_param:
      n: [25] #[5] #[75]  #,100,150]
      method_specific_processing: [True] #[True, False]
#      gene_key: ["highly_variable"]
      batch_key: "assay_sc" # the default behaviour is batch_key=None
    methods:
      spapros

evaluations:
  batch_aware_eval:
    batches: [batch_aware]
    selection_dataset: False
    datasets: [pbmc1k]
    dataset_param:
      processing: [lognorm]
    metrics: ["knn_overlap_X"]  # forest_clfs, gene_corr, cluster_similarity]