# when using relative paths: note that the working directory is the pwd of the terminal from where snakemake is run,
# this should be .../spapros-smk  (also possible: .../spapros-smk/workflow, might mess things up though)
DATA_DIR: /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data
DATA_DIR_TMP: /lustre/groups/ml01/workspace/lena.strasser/spapros-smk/data/tmp_data
RESULTS_DIR: results
SAVE_METHOD_SPECIFIC_OUTPUT: True # Whether to save method specific output of the selection methods (will be in RESULTS_DIR+"method_specific/{run}/")
PRELIMINARY_EVAL_SUMMARY: False # Whether to just summarise the currently available evaluation results and not run anything else.
# NOTE: PRELIMINARY_EVAL_SUMMARY can lead to wrong values for set ids that partially miss evaluation files!!!

selections:
#  batch_permutations:
#    datasets: [liver]
#    dataset_param:
#      processing: [lognorm]
#      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut.csv]
#      ct_key: [cell_type]
#    selection_param:
#      n: [50]
#      method_specific_processing: [False]
#      ct_key: [cell_type]
#      batch_key: [id] # the default behaviour is batch_key=None
#    methods:
#      spapros
#  batch_one_dataset:
#    datasets: [liver]
#    dataset_param:
#      processing: [lognorm]
#      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_one.csv]
#      ct_key: [ cell_type ]
#    selection_param:
##      n: [10, 15, 25, 50, 75, 100, 150, 200, 500, 1000]
#      n: [25, 50, 100, 200, 500, 1000]
#      method_specific_processing: [False]
#      ct_key: [cell_type]
#      batch_key: [id] # the default behaviour is batch_key=None
#    methods:
#      spapros
#  batch_permutations_bone_marrow:
#    datasets: [ bone_marrow ]
#    dataset_param:
#      processing: [ lognorm ]
#      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut.csv ]
#      ct_key: [ cell_type ]
#    selection_param:
#      n: [ 50 ]
#      method_specific_processing: [ False ]
#      ct_key: [ cell_type ]
#      batch_key: [ id ] # the default behaviour is batch_key=None
#    methods:
#      spapros
  batch_one_dataset_bone_marrow:
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut_one.csv ]
      ct_key: [ cell_type ]
    selection_param:
      #      n: [10, 15, 25, 50, 75, 100, 150, 200, 500, 1000]
      n: [ 25, 50, 100, 200, 500, 1000, 2000, 5000]
#      n: [25, 50, 100, 125, 250, 500, 1000, 2000, 4000, 8000]
      method_specific_processing: [ False ]
      ct_key: [ cell_type ]
      batch_key: [ id ] # the default behaviour is batch_key=None
    methods:
      spapros
  batch_pseudo_bone_marrow:
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut_one.csv ]
      ct_key: [ cell_type ]
    selection_param:
      #      n: [10, 15, 25, 50, 75, 100, 150, 200, 500, 1000]
      n: [ 8000 ]
      #      n: [25, 50, 100, 125, 250, 500, 1000, 2000, 4000, 8000]
      method_specific_processing: [ False ]
      ct_key: [ cell_type ]
      batch_key: [ id ] # the default behaviour is batch_key=None
    methods:
      pseudo
#  batch_permutations_four:
#    datasets: [liver_four]
#    dataset_param:
#      processing: [lognorm]
#      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_four_permut.csv]
#      ct_key: [cell_type]
#    selection_param:
#      n: [50]
#      method_specific_processing: [False]
#      ct_key: [cell_type]
#      batch_key: [id] # the default behaviour is batch_key=None
#    methods:
#      spapros
  batch_one_dataset_four:
    datasets: [liver_four]
    dataset_param:
      processing: [lognorm]
      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_four_permut_one.csv]
      ct_key: [ cell_type ]
    selection_param:
#      n: [10, 15, 25, 50, 75, 100, 150, 200, 500, 1000]
      n: [25, 50, 100, 200, 500, 1000, 2000, 5000]
      method_specific_processing: [False]
      ct_key: [cell_type]
      batch_key: [id] # the default behaviour is batch_key=None
    methods:
      spapros
  batch_pseudo_four:
    datasets: [ liver_four ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_four_permut_one.csv ]
      ct_key: [ cell_type ]
    selection_param:
      n: [ 8000 ]
      method_specific_processing: [ False ]
      ct_key: [ cell_type ]
      batch_key: [ id ] # the default behaviour is batch_key=None
    methods:
      pseudo

evaluations:
#  eval_on_full:
#    batches: [batch_permutations]
#    selection_dataset: False
#    datasets: [liver]
#    dataset_param:
#      processing: [lognorm]
#      ct_key: [ cell_type ]
#    metrics: [forest_clfs]  # forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_on_one:
#    batches: [batch_permutations]
#    selection_dataset: False
#    datasets: [liver]
#    dataset_param:
#      processing: [lognorm]
#      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_ones.csv]
#      ct_key: [ cell_type ]
#    metrics: [forest_clfs]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_var_one:
#    batches: [batch_one_dataset]
#    selection_dataset: False
#    datasets: [liver]
#    dataset_param:
#      processing: [lognorm]
#      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_ones.csv]
#      ct_key: [ cell_type ]
#    metrics: [forest_clfs, knn_overlap_X_id]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_on_full_bone_marrow:
#    batches: [ batch_permutations_bone_marrow ]
#    selection_dataset: False
#    datasets: [ bone_marrow ]
#    dataset_param:
#      processing: [ lognorm ]
#      ct_key: [ cell_type ]
#    metrics: [ forest_clfs ]  # forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_on_one_bone_marrow:
#    batches: [ batch_permutations_bone_marrow ]
#    selection_dataset: False
#    datasets: [ bone_marrow ]
#    dataset_param:
#      processing: [ lognorm ]
#      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut_one.csv ]
#      ct_key: [ cell_type ]
#    metrics: [ forest_clfs ]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
  eval_var_one_bone_marrow:
    batches: [ batch_one_dataset_bone_marrow, batch_pseudo_bone_marrow ]
    selection_dataset: False
    datasets: [ bone_marrow ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/bone_marrow_permut_one.csv ]
      ct_key: [ cell_type ]
    metrics: [ forest_clfs, knn_overlap_X_id, cluster_similarity ]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_on_full_liver_four:
#    batches: [ batch_permutations_four ]
#    selection_dataset: False
#    datasets: [ liver_four ]
#    dataset_param:
#      processing: [ lognorm ]
#      ct_key: [ cell_type ]
#    metrics: [ forest_clfs ]  # forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
  eval_on_one_liver_four:
    batches: [ batch_permutations_four, batch_pseudo_four ]
    selection_dataset: False
    datasets: [ liver_four ]
    dataset_param:
      processing: [ lognorm ]
      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_four_permut_one.csv ]
      ct_key: [ cell_type ]
    metrics: [ forest_clfs ]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
#  eval_var_one_liver_four:
#    batches: [ batch_one_dataset_four ]
#    selection_dataset: False
#    datasets: [ liver_four ]
#    dataset_param:
#      processing: [ lognorm ]
#      permutations: [ /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_four_permut_one.csv ]
#      ct_key: [ cell_type ]
#    metrics: [ forest_clfs, knn_overlap_X_id, cluster_similarity ]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]