# when using relative paths: note that the working directory is the pwd of the terminal from where snakemake is run,
# this should be .../spapros-smk  (also possible: .../spapros-smk/workflow, might mess things up though)
DATA_DIR: /lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data
DATA_DIR_TMP: /lustre/groups/ml01/workspace/lena.strasser/spapros-smk/data/tmp_data
RESULTS_DIR: results
SAVE_METHOD_SPECIFIC_OUTPUT: True # Whether to save method specific output of the selection methods (will be in RESULTS_DIR+"method_specific/{run}/")
PRELIMINARY_EVAL_SUMMARY: False # Whether to just summarise the currently available evaluation results and not run anything else.
# NOTE: PRELIMINARY_EVAL_SUMMARY can lead to wrong values for set ids that partially miss evaluation files!!!

selections:
  batch_permutations:
    datasets: [liver]
    dataset_param:
      processing: [lognorm]
      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut.csv]
    selection_param:
      n: [50]
      method_specific_processing: [True]
      ct_key: [cell_type]
      batch_key: [id] # the default behaviour is batch_key=None
    methods:
      spapros
  batch_one_dataset:
    datasets: [liver]
    dataset_param:
      processing: [lognorm]
      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_one.csv]
    selection_param:
#      n: [10, 15, 25, 50, 75, 100, 150, 200, 500, 1000]
      n: [25, 50, 100, 200, 500, 1000]
      method_specific_processing: [True]
      ct_key: [cell_type]
      batch_key: [id] # the default behaviour is batch_key=None
    methods:
      spapros

evaluations:
  eval_on_full:
    batches: [batch_permutations]
    selection_dataset: False
    datasets: [liver]
    dataset_param:
      processing: [lognorm]
    metrics: [forest_clfs]  # forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
  eval_on_one:
    batches: [batch_permutations]
    selection_dataset: False
    datasets: [liver]
    dataset_param:
      processing: [lognorm]
      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_ones.csv]
    metrics: [forest_clfs]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]
  eval_var_one:
    batches: [batch_one_dataset]
    selection_dataset: False
    datasets: [liver]
    dataset_param:
      processing: [lognorm]
      permutations: [/lustre/groups/ml01/workspace/lena.strasser/MA/benchmarking/data/test_data/permut_data/liver_permut_var_ones.csv]
    metrics: [forest_clfs, knn_overlap_X]  # [forest_clfs, gene_corr, cluster_similarity, knn_overlap_X]